working with init containers

diff --git a/confingMap-Secrets/configMap1.yaml b/confingMap-Secrets/configMap1.yaml
--- a/confingMap-Secrets/configMap1.yaml
+++ b/confingMap-Secrets/configMap1.yaml
@@ -25,15 +25,7 @@ spec:
         - configMapRef:
             name: configmap1
       command: ["sh","-c"]
-      args:
-        - > 
-          set -x;
-          for i in $PARAMS ; do 
-            var=\$$i ;
-            echo "$var";
-            sleep 5;
-          done
-          
+      args: ['for i in $PARAMS; do var="\$$i" ; [ -z `eval echo $var` ] && echo "variable is missing- $i" && exit 1 || echo "$i=$(eval echo $var)"']
 
           
             
